services:

  # ============================================================
  # BASE DE DATOS — MySQL
  # ============================================================
  mysql-db:
    image: mysql:8.0
    container_name: valledelsol-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - red-municipalidad
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root -p123456 --silent"]
      interval: 10s
      timeout: 10s
      retries: 30
      start_period: 90s

  # ============================================================
  # SERVICE REGISTRY — Eureka Server (:8761)
  # ============================================================
  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    container_name: valledelsol-eureka
    ports:
      - "8761:8761"
    networks:
      - red-municipalidad
    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --tries=1 --spider http://localhost:8761/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 12

  # ============================================================
  # MICROSERVICIO — Auth Service (:8080)
  # ============================================================
  auth-app:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: valledelsol-auth
    ports:
      - "8080:8080"
    depends_on:
      mysql-db:
        condition: service_healthy
      user-app:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/auth_vallesol_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQLDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SERVICES_USER_URL=http://user-app:8084
    networks:
      - red-municipalidad

  # ============================================================
  # MICROSERVICIO — User Service (:8084)
  # ============================================================

  user-app:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: valledelsol-user
    ports:
      - "8084:8084"
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/user_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQLDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - BREVO_SMTP_USER=${BREVO_SMTP_USER}
      - BREVO_SMTP_KEY=${BREVO_SMTP_KEY}
    networks:
      - red-municipalidad

  # ============================================================
  # MICROSERVICIO — Report Service (:8081)
  # ============================================================
  report-app:
    build:
      context: ./report-service
      dockerfile: Dockerfile
    container_name: valledelsol-reportes
    ports:
      - "8081:8081"
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/report_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQLDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - GEO_SERVICE_URL=http://geo-app:8082
      - ALERTAS_SERVICE_URL=http://alertas-app:8083
      - INCIDENT_SERVICE_URL=http://incident-app:8087
      - EVIDENCE_SERVICE_URL=http://evidence-app:8088
    networks:
      - red-municipalidad
      
  # ============================================================
  # MICROSERVICIO — Incident Service (:8087)
  # ============================================================
  incident-app:
    build:
      context: ./incident-service
      dockerfile: Dockerfile
    container_name: valledelsol-incident
    ports:
      - "8087:8087"
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/incident_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQLDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - red-municipalidad

  # ============================================================
  # MICROSERVICIO — Evidence Service (:8088)
  # ============================================================
  evidence-app:
    build:
      context: ./evidence-service
      dockerfile: Dockerfile
    container_name: valledelsol-evidence
    ports:
      - "8088:8088"
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/evidence_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQLDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - red-municipalidad          

  # ============================================================
  # MICROSERVICIO — Geo Service (:8082)
  # ============================================================
  geo-app:
    build:
      context: ./geo-service
      dockerfile: Dockerfile
    container_name: valledelsol-geo
    ports:
      - "8082:8082"
    depends_on:
      mysql-db:
        condition: service_healthy
      zone-app:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/geo_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQLDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - red-municipalidad

  # ============================================================
  # MICROSERVICIO — Zone Service (:8085)
  # ============================================================
  zone-app:
    build:
      context: ./zone-service
      dockerfile: Dockerfile
    container_name: valledelsol-zone
    ports:
      - "8085:8085"
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/zone_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQLDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - red-municipalidad

  # ============================================================
  # MICROSERVICIO — Brigade Service (:8086)
  # ============================================================
  brigade-app:
    build:
      context: ./brigade-service
      dockerfile: Dockerfile
    container_name: valledelsol-brigade
    ports:
      - "8086:8086"
    depends_on:
      mysql-db:
        condition: service_healthy
      zone-app:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/brigade_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQLDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - ZONE_SERVICE_URL=http://zone-app:8085
    networks:
      - red-municipalidad

  # ============================================================
  # MICROSERVICIO — Alert Service (:8083)
  # ============================================================
  alertas-app:
    build:
      context: ./alert-service
      dockerfile: Dockerfile
    container_name: valledelsol-alertas
    ports:
      - "8083:8083"
    depends_on:
      mysql-db:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/alert_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQLDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
    networks:
      - red-municipalidad

  # ============================================================
  # MICROSERVICIO — Notification Service (:8090)
  # ============================================================
  notification-app:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    container_name: valledelsol-notificaciones
    ports:
      - "8090:8090"
    depends_on:
      mysql-db:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      auth-app:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/notification_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQLDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - AUTH_SERVICE_URL=http://auth-app:8080
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - BREVO_SMTP_USER=${BREVO_SMTP_USER}
      - BREVO_SMTP_KEY=${BREVO_SMTP_KEY}
      - MAIL_FROM=w.vinet.h@gmail.com
    networks:
      - red-municipalidad

  # ============================================================
  # BFF — Orquestador (:8001)
  # ============================================================
  bff-app:
    build:
      context: ./bff-service
      dockerfile: Dockerfile
    container_name: valledelsol-bff
    ports:
      - "8001:8001"
    depends_on:
      eureka-server:
        condition: service_healthy
      auth-app:
        condition: service_started
      report-app:
        condition: service_started
      geo-app:
        condition: service_started
      alertas-app:
        condition: service_started
      notification-app:
        condition: service_started
      user-app:
        condition: service_started
      zone-app:
        condition: service_started
      brigade-app:
        condition: service_started
    environment:
      - MS_AUTH_URL=http://auth-app:8080
      - MS_REPORTES_URL=http://report-app:8081
      - MS_INCIDENT_URL=http://incident-app:8087
      - MS_GEO_URL=http://geo-app:8082
      - MS_USER_URL=http://user-app:8084
      - MS_ZONE_URL=http://zone-app:8085
      - MS_BRIGADE_URL=http://brigade-app:8086
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
    networks:
      - red-municipalidad

  # ============================================================
  # API GATEWAY (:8000) — Única puerta de entrada
  # ============================================================
  gateway-app:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: valledelsol-gateway
    ports:
      - "8000:8000"
    depends_on:
      - bff-app
    environment:
      - BFF_URL=http://bff-app:8001
      - JWT_SECRET_KEY=VGhpc0lzQVN1cGVyU2VjcmV0S2V5Rm9ySldUQXV0aFNlcnZpY2UxMjM0NTY=
    networks:
      - red-municipalidad

  # ============================================================
  # FRONTEND WEB — Angular/Ionic + Nginx (:8100)
  # ============================================================
  frontend-app:
    build:
      context: ./frontend-web
      dockerfile: Dockerfile
    container_name: valledelsol-frontend
    ports:
      - "8100:80"
    depends_on:
      - gateway-app
    networks:
      - red-municipalidad

  # ============================================================
  # FRONTEND ANDROID — App móvil servida via Nginx (:8101)
  # ============================================================
  android-app:
    build:
      context: ./frontend-android
      dockerfile: Dockerfile
    container_name: valledelsol-android
    ports:
      - "8101:80"
    depends_on:
      - gateway-app
    networks:
      - red-municipalidad

networks:
  red-municipalidad:
    driver: bridge

volumes:
  mysql-data:
