CREATE DATABASE IF NOT EXISTS auth_vallesol_db;
CREATE DATABASE IF NOT EXISTS report_db;
CREATE DATABASE IF NOT EXISTS geo_db;
CREATE DATABASE IF NOT EXISTS alert_db;
CREATE DATABASE IF NOT EXISTS notification_db;
CREATE DATABASE IF NOT EXISTS incident_db;