<<<<<<< HEAD
spring.application.name=alertas-service
server.port=8083

=======
spring.application.name=alert-service
server.port=8083


>>>>>>> 2008e67 (separacion de SolAlertas en alert-service y notification-service con Eureka)
spring.datasource.url=jdbc:mysql://localhost:3306/alert_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

<<<<<<< HEAD
auth.service.url=http://localhost:8080
geo.service.url=http://localhost:8081
reportes.service.url=http://localhost:8082
=======

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}
>>>>>>> 2008e67 (separacion de SolAlertas en alert-service y notification-service con Eureka)

spring.docker.compose.enabled=false
