server.port=8000
spring.application.name=api-gateway

# CONFIGURACIÓN MAESTRA DE CORS (DESACTIVA EL BLOQUEO DEL NAVEGADOR)
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:8100
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET, POST, OPTIONS, PUT, DELETE
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=true
