server.port=8001
spring.application.name=bff-vallesol

# =====================================================
# URLs de los Microservicios
# En Docker, cambiar localhost por nombres de contenedor
# =====================================================
ms.auth.url=http://localhost:8080
ms.reportes.url=http://localhost:8081
ms.geo.url=http://localhost:8082
ms.alertas.url=http://localhost:8083
